# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:

# Generic 3x5 - for keymap-editor testing
- board: nice_nano_v2
  shield: generic_3x5_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: generic_3x5_right

# Generic 3x6 - for keymap-editor testing
- board: nice_nano_v2
  shield: generic_3x6_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: generic_3x6_right

# Hillside 48
# - board: nice_nano_v2
#   shield: hillside48_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano_v2
#   shield: hillside48_right

# A_dux - Using generic_3x5
- board: nice_nano_v2
  shield: a_dux_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: a_dux_right

# Cradios - Using generic_3x5
- board: nice_nano_v2
  shield: cradios_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: cradios_right

# Corne - Using generic_3x6
- board: nice_nano_v2
  shield: corne_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y
- board: nice_nano_v2
  shield: corne_right

# Holy32
# - board: sparkfun_pro_micro_rp2040
#   shield: cradio_left
# - board: sparkfun_pro_micro_rp2040
#   shield: cradio_right

# Hypergolic (cradio36 - 3 thumbs, needs special handling)
# - board: nice_nano_v2
#   shield: cradio36_left
# - board: nice_nano_v2
#   shield: cradio36_right
