file_format: "1"
id: om
name: om
type: shield
url: https://github.com/Albert-IV/om-keyboard
requires: [pro_micro]
features:
  - keys
#  - encoder
#  - underglow
  - studio
siblings:
  - om_left
  - om_right