file_format: "1"
id: A_DUX
name: A_DUX
type: shield
url: https://github.cA_DUX/Albert-IV/A_DUX-keyboard
requires: [pro_micro]
features:
  - keys
#  - encoder
#  - underglow
  - studio
siblings:
  - a_dux_left
  - a_dux_8rightnm,887uikiu89 qwwwwwwwwwww747